### ISSUE TITLE
Summoner Spell 1 & 2 are not displayed

### ISSUE THREAD

**Issue by 0llii** [TimeBlaster/LeagueDeck#1]
When I join a game summoner spell 1 & 2 don't load. So there is just the small champion Icon but the key have no functionality. I tryed this in bot game and also a flexi game. Ult timer works fine. But it would be nice if there would be the opportunity to just write the spell key in the chat instead of the full summoner spell name.

**Comment by TimeBlaster** [comment]
There is a known bug with other languages than English.
I pull data from the in-game API and the summoner spell names are localized.
The next release will add support for all languages. Next week probably.

I can add a feature to only display the key for champion abilities instead of the full name.
For summoner spells I think it's better if the full name is shown.

**Comment by TimeBlaster** [comment]
fixed in v2.3
